config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]

  get 'angular-items', to: 'portfolios#angular'

  #Jeg excepter show, fordi jeg ikke vil have portfolios som flertal
  get 'portfolio/:id',  to: 'portfolios#show',  as: 'portfolio_show'
  #Dette betyder, at jeg f.eks. skal sætte portfolio_show_path i mine views, hvis jeg skal linke til et portfolio

  get 'about-me', to: 'pages#about'
  get 'contact', to:'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'


end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  has_many :technologies
  #DO not accept this if name is blank
  accepts_nested_attributes_for :technologies,
                                  reject_if: lambda {|attrs| attrs['name'].blank? }

  includes Placeholder

  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_potrfolio_items, -> {where(subtitle: 'Ruby on Rails')}

  #Kører efter neW, dvs. efter the form er kreeret
  #Dette er et callback
  #Defaults kan altså sætte i modellen eller i migration
  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height:'250', width: '250')
  end

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height:'600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height:'350', width: '200')
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
layout "portfolio"

  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item  = Portfolio.new(portfolio_params)

      respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: "Portfolio item is now live." }
      else
        format.html { render :new}
      end
    end
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])

  end

  def update
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "The record was successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end


  def destroy
    #Perform the lookup
    @portfolio_item = Portfolio.find(params[:id])
    #Destory/delete the lookup
    @portfolio_item.destroy
    #Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: "Record was successfully destroyed." }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                       :subtitle,
                                       :body,
                                       technologies_attributes: [:name])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with model: portfolio_item do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>

    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio items </h1>

<%= link_to "Create new Item", new_portfolio_path %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> </p>
  <p><%= portfolio_item.subtitle %> </p>
  <p><%= portfolio_item.body %> </p>
  <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %> </p>
  <%= link_to "Edit Item", edit_portfolio_path(portfolio_item) %>
  <%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>edit this portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio items </h1>

<%= link_to "Create new Item", new_portfolio_path %>

<% @portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> </p>
  <p><%= portfolio_item.subtitle %> </p>
  <p><%= portfolio_item.body %> </p>
  <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %> </p>
  <%= link_to "Edit Item", edit_portfolio_path(portfolio_item) %>
  <%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/new.html.erb
<h1>create a new portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

<h2>Technologies used:</h2>
<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>
 <% end %>